#+title: Typst Sources
#+author: Adam Zhang

This repository contains the [[https://typst.app][Typst]] sources for all of my formal academic papers.

* Compiled PDFs
** From GitHub Actions
A GitHub Actions workflow runs on every push commit and uploads a compiled PDF as an artifact. Either click the "Actions" tab to find the workflow for a specific commit, or look in the commit history for checkmarks.

On the dashboard for a workflow run, download the =pdf= artifact at the bottom of the page.
** Compiling Manually
To compile PDFs locally, you will need to install [[https://typst.app][Typst]]. Releases are available [[https://github.com/typst/typst/releases][here]]. Alternatively, you can enter a development shell using [[https://nixos.org][Nix]] with ~nix develop~, which comes with the Typst compiler.

Once Typst is installed, compiling documents is as simple as:
#+begin_src shell
typst c document.typ
#+end_src
* License
Given that this repository contains both software and academic works, this repository is under two separate licenses.

All software works are licensed under the MIT license. This includes all files and folders in the following list.
#+begin_example
.gitignore
.github
flake.nix
flake.lock
typstfmt.toml
#+end_example

A copy of the MIT license is available in the [[./LICENSE-CODE][LICENSE-CODE]] file.

All other files in this repository are licensed under the Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0) license. A copy of the CC BY-SA 4.0 license is available in the [[./LICENSE-CC][LICENSE-CC]] file.
