#set page(paper: "us-letter")
#set text(font: ("New Computer Modern", "Twitter Color Emoji"))

/* Requirements:
- A “welcome to AP Seminar” introductory paragraph.
- A summary of your personal experiences in taking this course.
- A “helpful hints” section that describes what study skills are most effective, how to organize your time, additional resources you would recommend, etc.
- A “what to avoid” section that describes mistakes you made that may have impacted your success in the class, common practices of many AP Seminar students that will prove to NOT be helpful or constructive to the students’ success in AP Seminar, etc.
- A concluding paragraph that contains “words of encouragement” to next year’s students. */

Dear future AP Seminar students,

Welcome to AP Seminar! In case you have no idea what this class is, and just signed up for it because why not---as I did---this is a class about research, writing, and presentation. If that's not what you signed up for---well, hopefully Mr. Sakole shows this to you early enough that you can still drop the course if you so choose. If you're still with us, then great---let's talk about what you're getting yourself into.

#show "AP": [AP#super(emoji.reg)]
This is an AP class. I'm sure you already knew that, and everything that comes with the package---the GPA boost, the end of year assessment, and all that. However, I want to emphasize a difference from the other number of AP classes dedicated juniors like you are inevitably taking: this class is *not* all about the AP exam. The exam is important---but only 45%-of-your-score important---it is a _minority_ of your score.

"Well then," I hear you asking. "Where is the other 55%?"

I'm glad you asked. Throughout the year, you will complete two "performance tasks". I'm sure you're familiar with "project-based assessments", probably from a social science course you've taken#footnote([I would be willing to bet you took AP World History, and have done the four PBAs that I did.])---think of performance tasks as PBAs, but scaled up by an order of magnitude. Rather than being relatively quick projects (that, admittedly, are just grade padding), these "performance tasks" are multi-month projects that will end up being a part of your AP score. I'm sure you can guess what these projects involve... if you guessed "research, writing, and presentation", congratulations, gold star for you.star.

If that sounds a bit scary, don't worry---honestly, it's not as bad as it sounds. In fact, grade-wise, this is probably the easiest AP class you could ever take; if you turn everything in on time, I can near-guarantee that you'll end every quarter with an A+. While I wouldn't go as far as to say this class is _easy_, it is definitely not as demanding as most AP classes. However, I do say this with a word of warning---the experience of the year is truly what *you* make of it. Personally, I found large portions of this class to be unenjoyable, but I don't fault the class for that; the main reason for my issues was my own tendencies to not stay on top of things, _especially_ the big deliverables#footnote([Of which, if you're curious, there are six.]). However, in retrospect, even with the stressful days and long nights that I had as a result of this class, I am still grateful for the skills that I have acquired from this class. No class that you can take#footnote([With the exception of AP Research, but you can't take that without taking this class first anyway.])---not even AP Lang---will prepare you better for _real-world_ writing and presentation than this class will.

That leads me into my next topic of interest---I want to prevent you from making the same mistakes that I did, because, trust me, I made many. If you take _nothing_ else away from this letter#footnote([I wouldn't blame you, I have already reached the word count requirement for this assignment and have plenty left to say; I know reading is hard sometimes, especially when you see walls of text.]), then please just take this word of advice and caution: *do not procrastinate*. Yes, this is coming from a chronic procrastinator, and yes, I know it is hard, and yes, I know it's not what you want to hear. But these are not your middle-school or freshman-year papers; as someone that left them until the last minute, trust me when I say you do *not* want to leave them until the last minute. These are papers that take genuine effort, genuine research, genuine thought, not something that you can bull\*\*\*\* your way through on the day before it's due---at least, not if you want a good AP score; and yes, that is coming from someone that did exactly that, and I can assure you that my papers were _not_ good.

I know writing papers is hard sometimes, and preparing for presentations is even harder---it feels like a monolith, a mountain that is hard to take the first step upon. My advice to you there is to break the mountain apart into small, surmountable hills. Mr. Sakole is a great teacher, and he will hand you the climbing boots, the ropes, and the picks, and show you the trail---in the forms of assignments like outlines and check-ins, designed to ensure that you're making progress. However, in the end, like I said---this class is ultimately in *your* hands. You have to take the first step onto the hill, and from there, you have to keep walking. Take small steps---climb the small hills. Perhaps you'll find some articles one night, put together an introduction the next night. Then you have to skip two nights, because you've got an AP US History exam coming up---that's alright. But remember to pick back up afterwards. Again, the absolute *worst* thing you can do is put it all off till the last night---you can't climb Mount Everest in a night#footnote([In fact, an average expedition takes around two months---which is, funnily enough, probably around the amount of time you'll have for a single performance task.]), no matter how much caffeine you have.

Another way to make it easier to not procrastinate is to *write about something you're interested in*. You'll have three opportunities to choose a research question throughout the year. Two of them will be with groups, so compromises will have to be made, and the third will be limited in the topic, so, again, compromises will have to be made. But don't be afraid to think outside of the box---choose a topic that interests you, that you won't hate spending weeks researching and writing about. The second-easiest way to make yourself miserable (after procrastination, of course) is to force yourself to spend hours learning about a topic you couldn't care less about.

I hate to say it, and I know you're tired of hearing it, but your junior year is going to be hard. That's okay---every function has a maximum, and I'm confident that you'll find your way through. Hopefully, when you reach the end of your year, and you find yourself in the position that I am in now---#strike([putting in way too much effort for a small, single-class assignment]) writing _your_ letter to the class of 2027---you can look back on the year, and feel proud of how far you've come. Remember, your junior year is going to be long---don't look up at the peak of the mountain. Only look down---look at how far you've come, and focus on the moment, on what you're doing *now*. Forget about the endless futures---all you can change is in the present moment.

Have an amazing year,

Adam Zhang
