[language-server.texlab.config]
texlab.build.onSave = true
texlab.build.auxDirectory = "out/"
texlab.build.logDirectory = "out/"
texlab.build.pdfDirectory = "out/"
texlab.build.executable = "tectonic"
texlab.build.args = [ "-X", "compile", "%f", "--synctex", "--outdir", "out/", "--keep-logs", "--keep-intermediates" ]
texlab.build.forwardSearchAfter = true
texlab.forwardSearch.executable = "zathura"
texlab.forwardSearch.args = ["--synctex-forward", "%l:1:%f", "%p"]
